---
/offline_process/vo:
  ros__parameters:
    use_sim_time: true
    Dataset:
      DatasetUsed: "Pohang04"
      Pohang04:
        bagPath: "/mnt/DataSmall/Boreas/ros2bag_boreas-2020-11-26-13-58/ros2bag_boreas-2020-11-26-13-58_0.db3"
        maxMemoryFootprint: 4.
        fullyLoadedTopics: [ "/gx5/imu_calib/data", "/gx5/baseline", "/gps/gps_nav_raw",
                             "/lidar_port/os_cloud_node/points", "/lidar_front/imu/data" ]
        autoLoading: True
        startOffset: 0.
        preDefinedDuration: 0.

      DELoco:
        bagPath: "/mnt/SSDSmall/Boreas/ros2bag_boreas-2020-11-26-13-58"
        maxMemoryFootprint: 4.
        fullyLoadedTopics: [ "/imu/data", ]
        autoLoading: True
        startOffset: 0.
        preDefinedDuration: 0.
