---
/offline_process/vo:
  ros__parameters:
    use_sim_time: true
    Dataset:
      DatasetUsed: "Pohang"
      Pohang:
        onlyDataPlaying: true
        bagFormate: "mcap"
        bagPath: "/mnt/DataBig/pohang/pohang04_100s"
        maxMemoryFootprint: 4.
        fullyLoadedTopics: [ "/gx5/imu_calib/data", "/gx5/baseline", "/gps/gps_nav_raw",
                             "/lidar_front/imu/data" ]
        autoLoading: True
        startOffset: 0.
        preDefinedDuration: 0.
        sensors: [ "imu", "reference", "gnss", "lidar", "lidar_imu" ]
        sensorTopics: [  "/gx5/imu_calib/data", "/gx5/baseline", "/gps/gps_nav_raw",
                         "/lidar_front/os_cloud_node/points", "/lidar_front/imu/data" ]
        excludedTopics: ["/lidar_front/imu/data", "/infrared/image", "/radar/image", "/lidar_front/os_cloud_node/points", ] # "/stereo_cam/left_img/compressed"

      DELoco:
        bagFormate: "sqlite"
        bagPath: "/mnt/SSDSmall/Boreas/ros2bag_boreas-2020-11-26-13-58"
        maxMemoryFootprint: 4.
        fullyLoadedTopics: [ "/imu/data", ]
        autoLoading: True
        startOffset: 0.
        preDefinedDuration: 0.
